services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"
    restart: always
    networks:
      - sami_network
    environment:
      - AGENT_URL=http://ai-agent:3000
      - PORT=5001
      - HOST=0.0.0.0
      - PRIVATE_KEY=${PRIVATE_KEY}
      - RPC_URL=${RPC_URL}

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3001"
    restart: always
    networks:
      - sami_network
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5001
      - PORT=3001

  ai-agent:
    build: ./packages/ai/sami
    ports:
      - "3000:3000"
    restart: always
    networks:
      - sami_network
    environment:
      - AGENT_URL=http://ai-agent:3000
      - PORT=3000

networks:
  sami_network:
    driver: bridge