# Etapa 1: Construcción
FROM node:23.3.0-slim AS builder
LABEL com.centurylinklabs.watchtower.enable="true"

WORKDIR /app

# Habilitar Corepack para usar Yarn 3+
RUN corepack enable \
    && corepack prepare yarn@3.2.3 --activate \
    && yarn set version 3.2.3

COPY . .

# Instalar dependencias antes de copiar el código fuente para aprovechar la cache
RUN yarn install


ARG NEXT_PUBLIC_ENVIRONMENT
ENV NEXT_PUBLIC_ENVIRONMENT=${NEXT_PUBLIC_ENVIRONMENT:-development}

RUN yarn backend:build

# Etapa 2: Producción
FROM node:23.3.0-slim

# -- Add curl and any other needed utilities
RUN apt-get update && apt-get install -y curl

WORKDIR /app

# Copia solo los archivos esenciales desde la etapa de construcción
COPY --from=builder /app/packages/backend/package*.json ./
COPY --from=builder /app/packages/backend/tsconfig.build.json ./
COPY --from=builder /app/packages/backend/node_modules ./node_modules
COPY --from=builder /app/packages/backend/dist ./dist

ARG NEXT_PUBLIC_ENVIRONMENT
ENV NEXT_PUBLIC_ENVIRONMENT=${NEXT_PUBLIC_ENVIRONMENT:-development} 

# Expone el puerto del backend
EXPOSE 5001

# Comando para ejecutar el backend
CMD ["node", "dist/server.js"]
