[profile.default]
solc_version   = "0.8.30"
src            = "contracts"
out            = "out"
libs           = ["lib"]
optimizer      = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./" }]


[rpc_endpoints]
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygon-amoy = "https://rpc-amoy.polygon.technology"
base    = "https://mainnet.base.org"
base-sepolia = "https://sepolia.base.org"

[etherscan]
polygon      = { key = "${ETHERSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
polygon-amoy = { key = "${ETHERSCAN_API_KEY}", url = "https://api-amoy.polygonscan.com/api" }
base         = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }
base-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

[fmt]
line_length     = 120
tab_width       = 4
quote_style     = "double"
bracket_spacing = true
int_types       = "long"
