name: Build & Deploy
env:
  IMAGE_TAG_BACKEND: ghcr.io/fabian416/sami/backend
  IMAGE_TAG_FRONTEND: ghcr.io/fabian416/sami/frontend
  IMAGE_TAG_AI_AGENT: ghcr.io/fabian416/sami/ai-agent

  IMAGE_VERSION: ${{ github.ref == 'refs/heads/production' && 'latest' || 'staging' }}

on:
  push:
    branches:
      - production
      - develop

jobs:
  build_backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Buildx Install
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.backend
          push: true
          tags: ${{env.IMAGE_TAG_BACKEND}}:${{env.IMAGE_VERSION}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build_frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Enable Corepack & Set Yarn version
        run: |
          corepack enable
          corepack prepare yarn@3.2.3 --activate

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Buildx Install
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.frontend
          push: true
          tags: ${{env.IMAGE_TAG_FRONTEND}}:${{env.IMAGE_VERSION}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build_ai_agent:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Buildx Install
        uses: docker/setup-buildx-action@v3

      - name: Build and Push AI Agent Image
        uses: docker/build-push-action@v5
        with:
          context: ./packages/ai/sami
          file: Dockerfile
          push: true
          tags: ${{env.IMAGE_TAG_AI_AGENT}}:${{env.IMAGE_VERSION}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
